### ISSUE TITLE
Unable to add tools which are not async generators

### ISSUE THREAD

**Issue by matejm** [zerodays/react-native-gen-ui#12]
## Current Behavior

Adding a tool which is an async generator works as it should. However in my case, tool will be a simple component displaying the data. No async requests are required. Cannot make typecheck to pass.

## Expected Behavior

I want to return a simple component, by type checker wants me to use async generators.

## Steps to Reproduce the Problem

  1. Follow the project setup in README.md
  2. Add the following tool:
  ```ts
hangmanStatus: {
    description: "Return the current status of the hangman game.",
    parameters: z.object({ state: z.string() }),
    render: (data) => ({
      data,
      component: <TextInput value={data.state} />,
    }),
  },
```
  3. Get a TS error
```
Type '{ data: { state: string; }; component: Element; }' is missing the following properties from type 'AsyncGenerator<ReactElement<any, string | JSXElementConstructor<any>>, ToolGeneratorReturn, unknown>': next, return, throw, [Symbol.asyncIterator]
``` 

## Environment

- Version: 1.2.3
- Platform: MacOS
- Node.js Version: v18.18.2

**Comment by zigapk** [comment]
Good point 😃
